apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: data-api
  namespace: default
spec:
  host: data-api
  subsets:
    - name: v1
      labels:
        app.kubernetes.io/name: data-api
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: data-api
  namespace: default
spec:
  hosts:
    - data-api
  http:
    - route:
        - destination:
            host: data-api
            subset: v1
          weight: 100
